spring.application.name=uberApp

#DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Data@base
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa,show-sql=true
spring.jpa.properties.hibernate.format_sql=true
hibernate.transaction.jta.platform = enable

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-location=classpath:data.sql

